### ISSUE TITLE
Problem compiling this project: resource-manager missing shared-jar folder

### ISSUE THREAD

**Issue by rgaglian** [NSO-developer/nso-xr-segmentrouting#1]
Hi,

This project does not compile "off the shelf" as the "shared-jar" folder is missing on the resource-manager package.

Package should look like:
ROGAGLIA-M-M0VW:resource-manager rogaglia$ ls -lat
total 160
drwxr-xr-x   3 rogaglia  staff    102 Oct 12 09:53 shared-jar           <---- MISSING
drwxr-xr-x   7 rogaglia  staff    238 Oct 12 09:53 load-dir
drwxr-xr-x  22 rogaglia  staff    748 Oct 12 09:53 .
drwxr-xr-x   3 rogaglia  staff    102 Oct 12 09:53 .package.mk
drwxr-xr-x   9 rogaglia  staff    306 Oct 12 09:44 ..
-rw-r--r--   1 rogaglia  staff   5643 Oct 12 09:44 CHANGES.txt
-rw-r--r--   1 rogaglia  staff    227 Oct 12 09:44 Jenkinsfile
-rw-r--r--   1 rogaglia  staff   1212 Oct 12 09:44 Makefile
-rw-r--r--   1 rogaglia  staff   7592 Oct 12 09:44 README.md
-rw-r--r--   1 rogaglia  staff     30 Oct 12 09:44 build-config.json
-rw-r--r--   1 rogaglia  staff    395 Oct 12 09:44 build-meta-data.xml
-rw-r--r--   1 rogaglia  staff   1970 Oct 12 09:44 coding_guidelines.md
-rw-r--r--   1 rogaglia  staff   2276 Oct 12 09:44 contributions.md
-rw-r--r--   1 rogaglia  staff     14 Oct 12 09:44 contributors.txt
drwxr-xr-x  10 rogaglia  staff    340 Oct 12 09:44 doc
drwxr-xr-x   3 rogaglia  staff    102 Oct 12 09:44 initial_data
-rw-r--r--   1 rogaglia  staff    922 Oct 12 09:44 package-meta-data.xml
-rw-r--r--   1 rogaglia  staff  31198 Oct 12 09:44 package.mk
drwxr-xr-x   3 rogaglia  staff    102 Oct 12 09:44 python
drwxr-xr-x   5 rogaglia  staff    170 Oct 12 09:44 src
drwxr-xr-x   4 rogaglia  staff    136 Oct 12 09:44 templates
drwxr-xr-x   7 rogaglia  staff    238 Oct 12 09:44 test
ROGAGLIA-M-M0VW:resource-manager rogaglia$

Roque

**Comment by pkrunals** [comment]
Ah! A resource manager is not compiled into. you will need to compile it separately as below.
1. 
cd packages/resource-manager/
make clean all
2. 
cd ../../
make all

I will update the read me file.

**Comment by rgaglian** [comment]
Hi, try with a clean checkout as I believe the package make file will not create the missing folder.
r.

**Comment by pkrunals** [comment]
Yes, try with clean checkout. 

Closing the issue
