### ISSUE TITLE
removing "augment ncs:services"

### ISSUE THREAD

**Issue by rgaglian** [NSO-developer/nso-xr-segmentrouting#2]
Hi,
Could we please remove this augment? It will prevent this package to work on a LSA environment.
Roque

**Comment by pkrunals** [comment]
Hi!
Could you please let me know what issue do you see with augmenting in LSA scenario? There was a requirement to specifically have it under /services tree.  On the second note about LSA, you could have Device's RFS (Fastmap) on the lower nodes and have the upper node still augment /services tree, that should not be an issue. 

Thanks

**Comment by rgaglian** [comment]
Hi,
I could but that would be a log threat. Basically you cannot build the RFS NED if you are are augmenting the ncs: tree. That is the reason why "augment ncs:services" is not longer in the default services skeleton nor a recommended implementation. This will be fix with "Common-data-models (CDM)", I believe.

BTW, you could always augment your own containers (like "sr:services")

Roque

**Comment by pkrunals** [comment]
Hi,
Here the focus is not for LSA. Requirements were to explicitly use ncs: services as it was easier for new users to understand the paradigm of services. 

I am closing this issue.
